// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    Bar: typeof import('./src/components/Echarts/Bar/index.vue')['default']
    BarList: typeof import('./src/components/Echarts/BarList/index.vue')['default']
    BarPie: typeof import('./src/components/Echarts/BarPie/index.vue')['default']
    BotLine: typeof import('./src/components/Echarts/BotLine/index.vue')['default']
    ConTable: typeof import('./src/components/ConTable/index.vue')['default']
    DialogPop: typeof import('./src/components/DialogPop/index.vue')['default']
    Distribution: typeof import('./src/components/Distribution/index.vue')['default']
    Hl: typeof import('./src/components/Echarts/Map/hl.vue')['default']
    Intro: typeof import('./src/components/Intro/index.vue')['default']
    Line: typeof import('./src/components/Echarts/Line/index.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Map: typeof import('./src/components/Echarts/Map/index.vue')['default']
    News: typeof import('./src/components/News/index.vue')['default']
    Pannel: typeof import('./src/components/Pannel/index.vue')['default']
    Paper: typeof import('./src/components/Paper/index.vue')['default']
    Pie: typeof import('./src/components/Echarts/Pie/index.vue')['default']
    PieCompar: typeof import('./src/components/Echarts/PieCompar/index.vue')['default']
    Politics: typeof import('./src/components/Politics/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/Service/index.vue')['default']
    ServiceBar: typeof import('./src/components/Echarts/ServiceBar/index.vue')['default']
    ServicePie: typeof import('./src/components/Echarts/ServicePie/index.vue')['default']
    ShowLine: typeof import('./src/components/Echarts/ShowLine/index.vue')['default']
    ShowNews: typeof import('./src/components/ShowNews/index.vue')['default']
    Slider: typeof import('./src/components/Slider/index.vue')['default']
    SubChooseTitle: typeof import('./src/components/SubChooseTitle/index.vue')['default']
    SubPannel: typeof import('./src/components/SubPannel/index.vue')['default']
    SubTitle: typeof import('./src/components/SubTitle/index.vue')['default']
    TipTitle: typeof import('./src/components/TipTitle/index.vue')['default']
    TopSubTitle: typeof import('./src/components/TopSubTitle/index.vue')['default']
    TopTitle: typeof import('./src/components/TopTitle/index.vue')['default']
    VideoList: typeof import('./src/components/VideoList/index.vue')['default']
  }
}

export {}
